#!/usr/bin/env python
import os
import sys
import json

# Load json data #
pathname = os.path.dirname(sys.argv[0])
containerPATH = os.path.abspath(pathname)
JSON_PATH = containerPATH + "/sources/data.json"

with open(JSON_PATH) as file:
	DATA = json.load(file)


if len(sys.argv) > 1:
	if sys.argv[1] in DATA:
		if len(sys.argv) == 2:
			command = "ping " + DATA[sys.argv[1]]["ip"]
		elif len(sys.argv) > 2:
			command = "ping " + DATA[sys.argv[1]]["ip"] + ' ' + ' '.join(sys.argv[2:])
		os.system(command)

	else:
		command = "ping " + ' '.join(sys.argv[1:])
		os.system(command)

else:
	command = "ping"
	os.system(command)
