#!/usr/bin/env python3

import yaml
from pathlib import Path
import os
import sys
from subprocess import check_call, DEVNULL, STDOUT

# Load yaml data #
pathname = os.path.dirname(sys.argv[0])
containerPATH = os.path.abspath(pathname)
YAML_PATH = containerPATH + "/sources/data.yml"

with open(YAML_PATH, 'r') as file:
	try:
		currentIpData = yaml.safe_load(file)
	except yaml.YAMLError as error:
		print(error)
		quit()

if len(sys.argv) < 2:
	sys.argv.append('NONE')

destination = sys.argv[1]

if destination in currentIpData:
	user = currentIpData[destination]["user"]
	IP = currentIpData[destination]["ip"]
	FULL = user + "@" + IP

	# Ping to test connction #
	try:
		command = ['ping', '-c', '1', currentIpData[destination]['ip']]
		response = check_call(command, stdout=DEVNULL, stderr=STDOUT)
	except CalledProcessError:
		response = 1
	if response == 0:
		print("Sending...")
	else:
		start = "###ERROR: Connection to "
		quit(start + destination + " (" + FULL + ") has failed.")

	# RUN SSH COMMAND #
	sendCommand = "ssh " + FULL
	os.system(sendCommand)


# If user input is not in ip dictionary
else:
	print("###ERROR: Desination not found")
	print("Desination options are: \n\t\t\t" + '\n\t\t\t'.join(currentIpData))
	quit("")
